version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gliderlabs/herokuish
    parallelism: 4
    steps:
      - checkout
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make shellcheck;; esac
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make lint;; esac
      - run: |
          make circleci
      - run: |
          make deps fpm package_cloud
      - run: |
          make build
      - run: |
          case $CIRCLE_NODE_INDEX in 0) basht tests/**/tests.sh ;; esac
      - run: |
          tests=$(circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings | xargs)
          echo "executing tests: $tests"
          basht $tests
      - store_artifacts:
          path: build
          destination: build
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              export PACKAGECLOUD_REPOSITORY=dokku/dokku
              make release release-packagecloud
            fi
  docker-build:
    machine: true
    working_directory: ~/gliderlabs/herokuish
    steps:
      - checkout
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run: |
          docker build -t $(IMAGE_NAME):$(BUILD_TAG)-18 --build-arg STACK_VERSION=18 .
      - run: |
          docker build -t $(IMAGE_NAME):$(BUILD_TAG)-20 --build-arg STACK_VERSION=20 .
      - run: |
          docker push $(IMAGE_NAME):$(BUILD_TAG)-18
      - run: |
          docker push $(IMAGE_NAME):$(BUILD_TAG)-20

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - docker-build:
          filters:
            tags:
              only: /^v.*/
